### ISSUE TITLE
Needs more info from documentation

### ISSUE THREAD

**Issue by Temtaime** [Sigkill79/sts#1]
Optimize function receives numVertices argument and it has to equal to max index in indices array.
But shouldn't it be named numVerticesMinusOne ?
Also what if indices begins not from zero(i.e. i want to optimize only second part of my indices array), is this accepted and will work ?

**Comment by Sigkill79** [comment]
Hi

I'm not sure where you see that numVertices has to be equal to max index in indices array, I can't find it right now at least. If that is the case then we need to fix something, since that would result in an out of bounds memory write.

You indices doesn't have to start at zero, but you have to ensure that the numVertices is the number of totalt vertices in the mesh. What you would do is to point the indices array to the first index you want to optimise and that numIndices is the number of indices you want to optimise.
